version: 1
update_configs:
  - package_manager: 'javascript'
    target_branch: 'dev'
    directory: '/'
    update_schedule: 'weekly'
    ignored_updates:
      - match:
          dependency_name: 'react'
      - match:
          dependency_name: 'react-dom'
